### ISSUE TITLE
New tool

### ISSUE THREAD

**Issue by JackyBorderCollie** [Byron-Inc/TBG#1]
What about adding a tool which sets a custom theme on the TBGs? It could be possible to make a custom theme that is not in the list of themes, and then enable it using that tool.

**Comment by Byron-Inc** [comment]
> What about adding a tool which sets a custom theme on the TBGs? It could be possible to make a custom theme that is not in the list of themes, and then enable it using that tool.

This website is actually intended to make quick tools that people may have to use multiple websites for, eg. dies, converter, a few specific calculators for certain topics, etc.

Thanks for your feedback anyway, I'll try to make it a browser extension in the future (if I know how to do it).
